<a href="https://colab.research.google.com/github/faithCoder1/Hamoye-DataScience/blob/master/Hamoye_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the module

In [1]:
import numpy as np

In [2]:
Hamoye = np.array([1,2,3,4,5,6])

In [3]:
type(Hamoye)

numpy.ndarray

Slice through the array

In [4]:
Hamoye[:3]

array([1, 2, 3])

In [5]:
Hamoye[3:]

array([4, 5, 6])

In [6]:
Hamoye[3:5]

array([4, 5])

In [7]:
Hamoye[3]=90
Hamoye

array([ 1,  2,  3, 90,  5,  6])

# Two Dimensional Array

In [8]:
Hamoye_2 = np.array([[1,2,3,4,5],[7,5,7,5,3]],int)

In [9]:
Hamoye_2

array([[1, 2, 3, 4, 5],
       [7, 5, 7, 5, 3]])

In [10]:
Hamoye_2[1,2]

7

In [11]:
Hamoye_2[0,:]

array([1, 2, 3, 4, 5])

In [12]:
Hamoye_2[-1:,-2:]

array([[5, 3]])

In [13]:
Hamoye_2.shape

(2, 5)

In [14]:
Hamoye_2[-2:,-3:]

array([[3, 4, 5],
       [7, 5, 3]])

In [15]:
Hamoye_2.dtype

dtype('int64')

In [16]:
len(Hamoye_2)

2

## The "in" statement for Np arrays

In [17]:
23 in Hamoye

False

In [18]:
Hamoye_ran =np.array(range(20),float)

In [19]:
Hamoye_ran = Hamoye_ran.reshape(5,4)

In [20]:
Hamoye_ran

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [21]:
a = np.array([1,2,3,4])
list(a)

[1, 2, 3, 4]

In [22]:
a.fill(0)

In [23]:
a

array([0, 0, 0, 0])

In [24]:
Hamoye_ran.transpose()

array([[ 0.,  4.,  8., 12., 16.],
       [ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.]])

In [25]:
Hamoye_ran.flatten() #useful for image processing

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

## Array Concatenation

In [27]:
a = np.array([3,5,7],float)
b = np.array([1,11],float)
c = np.array([5,8,9],float)
np.concatenate((a,b,c))

array([ 3.,  5.,  7.,  1., 11.,  5.,  8.,  9.])

In [28]:
x = np.array([[1,2,3],[4,7,9]],float)
y = np.array([[10,12,13],[14,17,19]],float)

In [29]:
np.concatenate((x,y))

array([[ 1.,  2.,  3.],
       [ 4.,  7.,  9.],
       [10., 12., 13.],
       [14., 17., 19.]])

In [30]:
np.concatenate((x,y),axis =0)

array([[ 1.,  2.,  3.],
       [ 4.,  7.,  9.],
       [10., 12., 13.],
       [14., 17., 19.]])

In [31]:
np.concatenate((x,y),axis =1)

array([[ 1.,  2.,  3., 10., 12., 13.],
       [ 4.,  7.,  9., 14., 17., 19.]])

## Creating other arrays

In [32]:
np.arange(20,dtype =float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [33]:
np.arange(1,20,3,dtype =float)

array([ 1.,  4.,  7., 10., 13., 16., 19.])

In [34]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Special 2D array

In [37]:
np.identity(5,dtype=float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.eye(5,k=-2,dtype= float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

## Array Mathematics